# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=70)),
                ('username', models.CharField(max_length=70, null=True)),
                ('contact', models.BigIntegerField()),
                ('secondary_contact', models.CharField(max_length=120, null=True)),
                ('registered_from', models.CharField(choices=[('ig', 'instagram'), ('fb', 'facebook'), ('tw', 'twitter'), ('ref', 'referral'), ('in_per', 'in_person')], max_length=20)),
                ('date_registered', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('buying_price', models.BigIntegerField()),
                ('sale_price', models.BigIntegerField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('date_added', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Product')),
            ],
        ),
    ]
