# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('cost_date', models.DateField()),
                ('cost_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creditors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.BigIntegerField()),
                ('description', models.TextField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Partial', 'Partially paid'), ('Fully_paid', 'Fully Paid'), ('Not_paid', 'Not Paid')], max_length=20)),
                ('date_paid', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_title', models.CharField(max_length=20)),
                ('ex_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=20)),
                ('ex_purpose', models.CharField(max_length=20)),
                ('ex_datecreated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MstOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(default='OrdNo11', max_length=20)),
                ('date_ordered', models.DateField()),
                ('delivery_date', models.DateField()),
                ('delivery_location', models.CharField(max_length=50)),
                ('delivery_fee', models.BigIntegerField(default=0)),
                ('total_price', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.BigIntegerField(default=0)),
                ('details', models.TextField()),
                ('mstOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MstOrder')),
                ('product', models.ManyToManyField(to='manager.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_amount', models.BigIntegerField()),
                ('rev_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rv_title', models.CharField(max_length=20)),
                ('rv_datecreated', models.DateField()),
                ('rv_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleNo', models.CharField(max_length=25)),
                ('description', models.TextField(null=True)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
                ('st_username', models.CharField(max_length=50)),
                ('employment_date', models.DateField()),
                ('st_role', models.CharField(max_length=50)),
                ('st_roledesc', models.TextField()),
                ('st_image', models.ImageField(upload_to='manager/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_from',
            field=models.CharField(choices=[('instagram', 'instagram'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('ref', 'referral'), ('in_per', 'in_person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='manager/images/'),
        ),
        migrations.AddField(
            model_name='sales',
            name='staff',
            field=models.ManyToManyField(to='manager.Staff'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Revenue_type'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Staff'),
        ),
        migrations.AddField(
            model_name='mstorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Customer'),
        ),
        migrations.AddField(
            model_name='mstorder',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Staff'),
        ),
        migrations.AddField(
            model_name='creditors',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Customer'),
        ),
        migrations.AddField(
            model_name='creditors',
            name='mstOrder',
            field=models.ManyToManyField(to='manager.MstOrder'),
        ),
        migrations.AddField(
            model_name='costs',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Expense_type'),
        ),
        migrations.AddField(
            model_name='costs',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Staff'),
        ),
    ]
