# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190424_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(blank=True, upload_to='img/profile_image')),
                ('description', models.TextField()),
                ('website', models.URLField(default='')),
                ('contact', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='img/products'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='st_image',
            field=models.ImageField(blank=True, upload_to='img/staff'),
        ),
    ]
