# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-10 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190426_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='rev_desc',
            field=models.TextField(null=True),
        ),
    ]
