# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_revenue_rev_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('amount', models.IntegerField()),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=20)),
                ('date_set', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='creditors',
            name='mstOrder',
        ),
        migrations.AddField(
            model_name='creditors',
            name='mstOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.MstOrder'),
        ),
    ]
